"""Add discovered_podcasts table

Revision ID: 5b1d89589c33
Revises: d0ac71e7cd13
Create Date: 2026-03-28 10:51:03.785664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1d89589c33'
down_revision: Union[str, Sequence[str], None] = 'd0ac71e7cd13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_podcasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('latest_episode_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('listen_score', sa.Float(), nullable=True),
    sa.Column('itunes_rating', sa.Float(), nullable=True),
    sa.Column('itunes_review_count', sa.Integer(), nullable=True),
    sa.Column('podcastindex_trending', sa.Float(), nullable=True),
    sa.Column('quality_rank', sa.Float(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('api_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('promoted_source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['promoted_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discovered_podcasts')
    # ### end Alembic commands ###
